FROM postgres:latest

LABEL maintainer="Hana Bouacila <ih_bouacila@esi.dz>, Yousra Fantazi <iy_fantazi@esi.dz>"

USER root

RUN export LANGUAGE=en_US.UTF-8
#adds the schema files to the metastore database 
#ADD hive-conf/hive-schema-3.1.0.postgres.sql /hive/hive-schema-3.1.0.postgres.sql
#ADD config/hive-txn-schema-2.3.0.postgres.sql /hive/hive-txn-schema-2.3.0.postgres.sql
#COPY hive-conf/init-hive-db.sh /docker-entrypoint-initdb.d/init-user-db.sh
#RUN chmod +x /docker-entrypoint-initdb.d/init-user-db.sh 

